// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtfV_w1sq6pLKUHJXRD3eeLkwl5OxMkG4',
    appId: '1:134466005931:web:dbfbb7d172a4ea946340ee',
    messagingSenderId: '134466005931',
    projectId: 'idea-catcher01',
    authDomain: 'idea-catcher01.firebaseapp.com',
    storageBucket: 'idea-catcher01.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw5hwxdJ9ifrCtKEb6QWFYo7FOr7ipYIU',
    appId: '1:134466005931:android:8b526eae520f395f6340ee',
    messagingSenderId: '134466005931',
    projectId: 'idea-catcher01',
    storageBucket: 'idea-catcher01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_n5djkDZPXZjn1rUkS-eXg3--1xEjGNo',
    appId: '1:134466005931:ios:20960130f05880256340ee',
    messagingSenderId: '134466005931',
    projectId: 'idea-catcher01',
    storageBucket: 'idea-catcher01.appspot.com',
    iosClientId: '134466005931-qoj3stmdd7hi367v05ljekv0umd7sfs3.apps.googleusercontent.com',
    iosBundleId: 'com.bartosztomaszewski.catchem',
  );
}
